apiVersion: v1
kind: Pod
metadata:
     name: node-express
     labels:
       app.kubernetes.io/name: node-express
       app.kubernetes.io/version: 0.0.1
spec:
    containers:
     - name: server
       image: iocanel/node-express:0.0.1
       ports:
         - containerPort: 3000
           name: http
           protocol: TCP
       livenessProbe:
         httpGet:
           path: /
           port: 3000
         initialDelaySeconds: 5
         periodSeconds: 10
       readinessProbe:
         httpGet: 
           path: /
           port: 3000
         initialDelaySeconds: 1 
         periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: node-express
    app.kubernetes.io/version: 0.0.1
  name: node-express
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app.kubernetes.io/name: node-express
    app.kubernetes.io/version: 0.0.1
  type: ClusterIP
